workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      groups:
        - ios_credentials
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Set up code signing
        script: |
          cd ios/App
          xcode-project use-profiles --project App.xcodeproj

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            archive

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

    artifacts:
      - ios/App/build/export/*.ipa
