workflows:
  ios-capacitor:
    name: iOS Capacitor Build (App Store IPA)
    max_build_duration: 60

    environment:
      groups:
        - ios_credentials
      node: 22
      xcode: latest

      ios_signing:
        provisioning_profiles:
          - ios_appstore_22450
        certificates:
          - ios_distribution_cert_v3

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Debug signing files exist
        script: |
          echo "== Provisioning Profiles dir =="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          echo "== Certificates dir =="
          ls -la "$HOME/Library/MobileDevice/Certificates" || true
          echo "== ExportOptions.plist =="
          ls -la ios/App/ExportOptions.plist

      - name: Apply code signing profiles (Codemagic)
        script: |
          cd ios/App
          xcode-project use-profiles --project App.xcodeproj

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            archive

      - name: Export IPA (App Store)
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

    artifacts:
      - ios/App/build/export/*.ipa
      - ios/App/build/**/*.xcarchive
