workflows:
  ios-capacitor:
    name: iOS Capacitor Build (App Store IPA + Upload)
    max_build_duration: 60

    environment:
      groups:
        - ios_credentials
      node: 22
      xcode: latest

      ios_signing:
        provisioning_profiles:
          - ios_appstore_22450
        certificates:
          - ios_distribution_cert_v3

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Debug signing files exist
        script: |
          echo "== Provisioning Profiles dir =="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          echo "== Certificates dir =="
          ls -la "$HOME/Library/MobileDevice/Certificates" || true

      - name: Apply code signing profiles (Codemagic)
        script: |
          set -e
          cd ios/App
          xcode-project use-profiles --project App.xcodeproj

      - name: Set iOS build number (Build 2)
        script: |
          set -e
          cd ios/App

          # Preferred: agvtool (requires Apple Generic Versioning enabled)
          if agvtool new-version -all 2; then
            echo "agvtool OK"
            agvtool what-version
          else
            echo "agvtool failed, applying fallback by editing Info.plist CFBundleVersion..."
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion 2" App/App/Info.plist
            echo "CFBundleVersion is now:"
            /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" App/App/Info.plist
          fi

      - name: Verify Info.plist privacy keys exist (prevents ITMS-90683)
        script: |
          set -e
          /usr/libexec/PlistBuddy -c "Print :NSPhotoLibraryUsageDescription" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Print :NSLocationWhenInUseUsageDescription" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Print :NSLocationAlwaysAndWhenInUseUsageDescription" ios/App/App/Info.plist

      - name: Build iOS archive
        script: |
          set -e
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            archive

      - name: Generate ExportOptions.plist from installed App Store profile
        script: |
          set -e
          cd ios/App

          BUNDLE_ID="gr.studiom.app22450"
          TEAM_ID="$APPLE_TEAM_ID"
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"

          FOUND_NAME=""

          for p in "$PROFILES_DIR"/*.mobileprovision; do
            security cms -D -i "$p" > /tmp/profile.plist
            APP_ID=$(/usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" /tmp/profile.plist 2>/dev/null || true)
            NAME=$(/usr/libexec/PlistBuddy -c "Print :Name" /tmp/profile.plist 2>/dev/null || true)

            if echo "$APP_ID" | grep -q "\.${BUNDLE_ID}$"; then
              FOUND_NAME="$NAME"
              break
            fi
          done

          if [ -z "$FOUND_NAME" ]; then
            echo "ERROR: Δεν βρέθηκε App Store provisioning profile που να ταιριάζει στο bundle id $BUNDLE_ID"
            exit 1
          fi

          cat > ExportOptions.generated.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${FOUND_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Export IPA (App Store)
        script: |
          set -e
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.generated.plist \
            -exportPath build/export

      - name: Upload IPA to App Store Connect (no Codemagic publishing)
        script: |
          set -e
          cd ios/App

          IPA_PATH=$(ls -1 build/export/*.ipa | head -n 1)
          echo "IPA: $IPA_PATH"

          KEY_ID="$APP_STORE_CONNECT_KEY_ID"
          ISSUER_ID="$APP_STORE_CONNECT_ISSUER_ID"

          mkdir -p "$HOME/.private_keys"

          # Write the .p8 safely:
          # - convert literal "\n" to real newlines (if stored that way)
          # - remove Windows CRLF (\r)
          python3 - <<'PY'
          import os
          key_id = os.environ["APP_STORE_CONNECT_KEY_ID"]
          raw = os.environ["APP_STORE_CONNECT_PRIVATE_KEY"]

          if "\\n" in raw and "BEGIN PRIVATE KEY" in raw:
            raw = raw.replace("\\n", "\n")

          raw = raw.replace("\r", "")

          path = os.path.expanduser(f"~/.private_keys/AuthKey_{key_id}.p8")
          with open(path, "w", newline="\n") as f:
            f.write(raw.strip() + "\n")
          print("Wrote:", path)
          PY

          chmod 600 "$HOME/.private_keys/AuthKey_${KEY_ID}.p8"

          # Non-secret sanity check
          echo "Key file first line:"
          head -n 1 "$HOME/.private_keys/AuthKey_${KEY_ID}.p8"
          echo "Key file last line:"
          tail -n 1 "$HOME/.private_keys/AuthKey_${KEY_ID}.p8"

          # Upload
          if xcrun altool --help >/dev/null 2>&1; then
            echo "Uploading with altool..."
            xcrun altool --upload-app \
              --type ios \
              --file "$IPA_PATH" \
              --apiKey "$KEY_ID" \
              --apiIssuer "$ISSUER_ID" \
              --verbose
          else
            echo "altool not found, uploading with iTMSTransporter..."
            xcrun iTMSTransporter -m upload \
              -assetFile "$IPA_PATH" \
              -apiKey "$KEY_ID" \
              -apiIssuer "$ISSUER_ID" \
              -v informational
          fi

    artifacts:
      - ios/App/build/export/*.ipa
      - ios/App/build/**/*.xcarchive
      - ios/App/ExportOptions.generated.plist
