workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - ios/App/build/**/*.xcarchive
